# Generated by Django 3.0 on 2025-03-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
